"""Auditable JEPA Anything core primitives."""

from .audit import (
    BasisGeometryReport,
    FactorGeometryReport,
    OPFGeometryReport,
    RoundTripReport,
    TransposeSynthesisReport,
    audit_basis_geometry,
    audit_factor_geometry,
    audit_opf_geometry,
    audit_state_round_trip,
    audit_transpose_synthesis,
)
from .baselines import (
    CapacityMatchReport,
    JEPAPrediction,
    MLPPredictor,
    StandardJEPABaseline,
    UnconstrainedMultiHeadJEPABaseline,
    UnconstrainedMultiHeadPredictor,
    build_capacity_matched_predictors,
    capacity_match_report,
    ema_update,
    parameter_count,
)
from .losses import (
    JEPAAnythingLoss,
    OnlineVarianceLoss,
    OnlineVarianceTracker,
    encoder_variance_loss,
    factor_activity_loss,
    factor_coordinate_standard_deviation,
    factor_cross_correlation,
    factor_decorrelation_loss,
    factor_orthogonality_loss,
    factor_prediction_loss,
    factor_standard_deviation,
    jepa_anything_objective,
    online_encoder_variance_loss,
    online_variance_loss,
    projector_orthogonality_loss,
    streaming_factor_activity_loss,
)
from .opf import (
    ORTHOGONALITY_MODES,
    OrthogonalFactorProjection,
    OrthogonalityMode,
    compose_state,
    decompose_state,
    default_geometry_tolerance,
    is_orthonormal_basis,
    orthonormalize_basis,
    project_state,
    transpose_synthesize_state,
    validate_factorization,
)
from .sigreg import SIGReg, SIGRegReduction, epps_pulley_statistic

__version__ = "0.4.0"

__all__ = [
    "BasisGeometryReport",
    "CapacityMatchReport",
    "FactorGeometryReport",
    "JEPAPrediction",
    "JEPAAnythingLoss",
    "MLPPredictor",
    "OPFGeometryReport",
    "OnlineVarianceLoss",
    "OnlineVarianceTracker",
    "ORTHOGONALITY_MODES",
    "OrthogonalFactorProjection",
    "OrthogonalityMode",
    "RoundTripReport",
    "SIGReg",
    "SIGRegReduction",
    "StandardJEPABaseline",
    "UnconstrainedMultiHeadJEPABaseline",
    "UnconstrainedMultiHeadPredictor",
    "TransposeSynthesisReport",
    "audit_basis_geometry",
    "audit_factor_geometry",
    "audit_opf_geometry",
    "audit_state_round_trip",
    "audit_transpose_synthesis",
    "build_capacity_matched_predictors",
    "capacity_match_report",
    "compose_state",
    "decompose_state",
    "default_geometry_tolerance",
    "ema_update",
    "epps_pulley_statistic",
    "encoder_variance_loss",
    "factor_activity_loss",
    "factor_coordinate_standard_deviation",
    "factor_cross_correlation",
    "factor_decorrelation_loss",
    "factor_orthogonality_loss",
    "factor_prediction_loss",
    "factor_standard_deviation",
    "is_orthonormal_basis",
    "jepa_anything_objective",
    "online_encoder_variance_loss",
    "online_variance_loss",
    "orthonormalize_basis",
    "parameter_count",
    "project_state",
    "projector_orthogonality_loss",
    "streaming_factor_activity_loss",
    "transpose_synthesize_state",
    "validate_factorization",
]
